routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('logout', 'Auth\LoginController@logout');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/main', 'HomeController@main')->name('home.main');
    Route::get('/noautorizado/{tipo}', 'HomeController@noautorizado')->name('home.noautorizado');
    Route::get('emisor', 'HomeController@emisor')->name('home.emisor');
    Route::get('receptor', 'HomeController@receptor')->name('home.receptor');
    Route::post('categoriamenu/buscar', 'CategoriamenuController@buscar')->name('categoriamenu.buscar');
    Route::get('categoriamenu/eliminar/{id}/{listarluego}', 'CategoriamenuController@eliminar')->name('categoriamenu.eliminar');
    Route::resource('categoriamenu', 'CategoriamenuController', array('except' => array('show')));

    Route::post('opcionmenu/buscar', 'OpcionmenuController@buscar')->name('opcionmenu.buscar');
    Route::get('opcionmenu/eliminar/{id}/{listarluego}', 'OpcionmenuController@eliminar')->name('opcionmenu.eliminar');
    Route::resource('opcionmenu', 'OpcionmenuController', array('except' => array('show')));

    Route::post('tipousuario/buscar', 'TipousuarioController@buscar')->name('tipousuario.buscar');
    Route::get('tipousuario/obtenerpermisos/{listar}/{id}', 'TipousuarioController@obtenerpermisos')->name('tipousuario.obtenerpermisos');
    Route::post('tipousuario/guardarpermisos/{id}/{permiso_id}/{accion}', 'TipousuarioController@guardarpermisos')->name('tipousuario.guardarpermisos');
    Route::get('tipousuario/eliminar/{id}/{listarluego}', 'TipousuarioController@eliminar')->name('tipousuario.eliminar');
    Route::resource('tipousuario', 'TipousuarioController', array('except' => array('show')));

    Route::resource('usuario', 'UsuarioController');
    Route::post('usuario/buscar', 'UsuarioController@buscar')->name('usuario.buscar');
    Route::get('usuario/eliminar/{id}/{listarluego}', 'UsuarioController@eliminar')->name('usuario.eliminar');
    Route::get('usuario/autocompletarrepresentante/{querysearch}', 'UsuarioController@autocompletarrepresentante')->name('usuario.autocompletarrepresentante');
    Route::get('usuario/activarusuario/{id}/{listarluego}', 'UsuarioController@activarusuario')->name('usuario.activarusuario');
    Route::post('usuario/activarcuenta/{id}', 'UsuarioController@activarcuenta')->name('usuario.activarcuenta');
    Route::get('usuario/editclave/{id}', 'UsuarioController@editclave')->name('usuario.editclave');
    Route::put('usuario/updateclave/{id}', 'UsuarioController@updateclave')->name('usuario.updateclave');
    Route::get('usuario/editdatos/{id}', 'UsuarioController@editdatos')->name('usuario.editdatos');
    Route::put('usuario/updatedatos/{id}', 'UsuarioController@updatedatos')->name('usuario.updatedatos');

    Route::post('permiso/buscar', 'PermisoController@buscar')->name('permiso.buscar');
    Route::get('permiso/eliminar/{id}/{listarluego}', 'PermisoController@eliminar')->name('permiso.eliminar');
    Route::resource('permiso', 'PermisoController', array('except' => array('show')));

    Route::post('empresa/buscar', 'EmpresaController@buscar')->name('empresa.buscar');
    Route::get('empresa/eliminar/{id}/{listarluego}', 'EmpresaController@eliminar')->name('empresa.eliminar');
    Route::resource('empresa', 'EmpresaController', array('except' => array('show')));

    Route::post('representante/buscar', 'RepresentanteController@buscar')->name('representante.buscar');
    Route::get('representante/eliminar/{id}/{listarluego}', 'RepresentanteController@eliminar')->name('representante.eliminar');
    Route::resource('representante', 'RepresentanteController', array('except' => array('show')));

    Route::post('tipodocumento/buscar', 'TipodocumentoController@buscar')->name('tipodocumento.buscar');
    Route::get('tipodocumento/eliminar/{id}/{listarluego}', 'TipodocumentoController@eliminar')->name('tipodocumento.eliminar');
    Route::resource('tipodocumento', 'TipodocumentoController', array('except' => array('show')));

    Route::post('metadata/buscar', 'MetadataController@buscar')->name('metadata.buscar');
    Route::get('metadata/eliminar/{id}/{listarluego}', 'MetadataController@eliminar')->name('metadata.eliminar');
    Route::resource('metadata', 'MetadataController', array('except' => array('show')));

    Route::post('flujotrabajo/buscar', 'FlujotrabajoController@buscar')->name('flujotrabajo.buscar');
    Route::get('flujotrabajo/eliminar/{id}/{listarluego}', 'FlujotrabajoController@eliminar')->name('flujotrabajo.eliminar');
    Route::get('flujotrabajo/verdocumentos/{flujotrabajo_id}', 'FlujotrabajoController@verdocumentos')->name('flujotrabajo.documentos');
    Route::resource('flujotrabajo', 'FlujotrabajoController', array('except' => array('show')));

    Route::post('documento/buscar', 'DocumentoController@buscar')->name('documento.buscar');
    Route::post('documento/guardar', 'DocumentoController@guardar')->name('documento.guardar');
    Route::get('documento/eliminar/{id}/{listarluego}', 'DocumentoController@eliminar')->name('documento.eliminar');
    Route::get('documento/emitir', 'DocumentoController@emitir')->name('documento.emitir');
    Route::get('documento/generarmetadata/{tipodocumento_id}/{documento_id?}', 'DocumentoController@generarmetadata')->name('documento.generarmetadata');
    Route::resource('documento', 'DocumentoController');

    Route::post('datos/buscar', 'DatosController@buscar')->name('datos.buscar');
    Route::get('datos/eliminar/{id}/{listarluego}', 'DatosController@eliminar')->name('datos.eliminar');
    Route::resource('datos', 'DatosController', array('except' => array('show')));

    Route::post('tarea/buscar', 'TareaController@buscar')->name('tarea.buscar');
    Route::get('tarea/eliminar/{id}/{listarluego}', 'TareaController@eliminar')->name('tarea.eliminar');
    Route::resource('tarea', 'TareaController', array('except' => array('show')));

    Route::post('bitacora/buscar', 'BitacoraController@buscar')->name('bitacora.buscar');
    Route::get('bitacora/eliminar/{id}/{listarluego}', 'BitacoraController@eliminar')->name('bitacora.eliminar');
    Route::resource('bitacora', 'BitacoraController', array('except' => array('show')));

    Route::post('respuesta/buscar', 'RespuestaController@buscar')->name('respuesta.buscar');
    Route::get('respuesta/eliminar/{id}/{listarluego}', 'RespuestaController@eliminar')->name('respuesta.eliminar');
    Route::resource('respuesta', 'RespuestaController', array('except' => array('show')));

    Route::post('detalleflujotrabajo/buscar', 'DetalleflujotrabajoController@buscar')->name('detalleflujotrabajo.buscar');
    Route::get('detalleflujotrabajo/eliminar/{id}/{listarluego}', 'DetalleflujotrabajoController@eliminar')->name('detalleflujotrabajo.eliminar');
    Route::resource('detalleflujotrabajo', 'DetalleflujotrabajoController', array('except' => array('show')));

    Route::post('seguimiento/buscar', 'SeguimientoController@buscar')->name('seguimiento.buscar');
    Route::get('seguimiento/eliminar/{id}/{listarluego}', 'SeguimientoController@eliminar')->name('seguimiento.eliminar');
    Route::get('seguimiento/buscartareas/{flujotrabajo_id}', 'SeguimientoController@buscartareas')->name('seguimiento.buscartareas');
    Route::get('seguimiento/documentosportarea/{detalleflujotrabajo_id}', 'SeguimientoController@documentosportarea')->name('seguimiento.documentosportarea');
    Route::resource('seguimiento', 'SeguimientoController', array('except' => array('show')));

    Route::post('seguimiento/buscaremisor', 'SeguimientoController@buscaremisor')->name('seguimiento.buscaremisor');
    Route::get('seguimiento/buscartareasemisor/{flujotrabajo_id}', 'SeguimientoController@buscartareasemisor')->name('seguimiento.buscartareasemisor');
    Route::get('seguimiento/documentosportareaemisor/{detalleflujotrabajo_id}', 'SeguimientoController@documentosportareaemisor')->name('seguimiento.documentosportareaemisor');

    Route::post('regla/buscar', 'ReglaController@buscar')->name('regla.buscar');
    Route::get('regla/eliminar/{id}/{listarluego}', 'ReglaController@eliminar')->name('regla.eliminar');
    Route::resource('regla', 'ReglaController', array('except' => array('show')));

    Route::post('historial/buscar', 'HistorialController@buscar')->name('historial.buscar');
    Route::get('historial/eliminar/{id}/{listarluego}', 'HistorialController@eliminar')->name('historial.eliminar');
    Route::resource('historial', 'HistorialController', array('except' => array('show')));
    Route::get('historial/documento/{documento}', 'HistorialController@historialdocumento')->name('historial.historialdocumento');
    Route::get('historial/verarchivos', 'HistorialController@verarchivos')->name('historial.verarchivos');

    Route::post('metadataregla/buscar', 'MetadatareglaController@buscar')->name('metadataregla.buscar');
    Route::get('metadataregla/eliminar/{id}/{listarluego}', 'MetadatareglaController@eliminar')->name('metadataregla.eliminar');
    Route::resource('metadataregla', 'MetadatareglaController', array('except' => array('show')));

    Route::post('respuestadetalleflujo/buscar', 'RespuestadetalleflujoController@buscar')->name('respuestadetalleflujo.buscar');
    Route::get('respuestadetalleflujo/eliminar/{id}/{listarluego}', 'RespuestadetalleflujoController@eliminar')->name('respuestadetalleflujo.eliminar');
    Route::resource('respuestadetalleflujo', 'RespuestadetalleflujoController', array('except' => array('show')));

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\URL;

class User extends Authenticatable
{
    use Notifiable;
    protected $table = 'usuario';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * @param $query
     * @param $querysearch
     * @return mixed
     */
    public function scopelistar($query, $querysearch)
    {
        return $query->where(function ($subquery) use ($querysearch) {
            if (!is_null($querysearch)) {
                $subquery->orwhere('name', 'LIKE', '%' . $querysearch . '%')
                    ->orwhere('email', 'LIKE', '%' . $querysearch . '%');
            }
        })->orderBy('name', 'ASC');
    }

    /**
     * @return BelongsTo
     */
    public function representante()
    {
        return $this->belongsTo('App\Representante', 'representante_id');
    }

    /**
     * @return HasMany
     */
    public function tiposusuarios()
    {
        return $this->hasMany('App\Tipousuariousuario', 'usuario_id');
    }

    /**
     * @return BelongsToMany
     */
    public function tipousuarios()
    {
        return $this->belongsToMany('App\Tipousuario', 'tipousuario_usuario', 'usuario_id', 'tipousuario_id');

    }

    /**
     * @return HasOne
     */
    public function unicotipousuario()
    {
        return $this->hasOne('App\Tipousuariousuario', 'usuario_id');
    }

    /**
     * @return mixed
     */
    public function getAvatarUrlAttribute()
    {
        return URL::to('/') . Storage::url('public/avatars/' . $this->id . '/' . $this->avatar);
    }
}

resources/views/dashboard/401.blade.php
<div id="cabecerahome" class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <div class="d-flex justify-content-center">
                <h1 class="text-danger">Error 401: No tiene permisos suficientes</h1>
            </div>
        </div>
    </div>
</div>
<div class="content" id="contenido">
    <div class="row">
        <div class="col-xl-12">
            <!-- Traffic sources -->
            <div class="card">
                <div class="card-header header-elements-inline">
                    <h3 class="card-title text-info"><i class="icon-user-lock"></i> Mensaje del sistema</h3>
                </div>
                <div class="card-body">
                    <h5 class="text-monospace">Contacte con el administrador del sistema para que le conceda los permisos necesarios</h5>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/dashboard/emisor.blade.php
<!-- Main charts -->
<div class="row">
    <div class="col-xl-12">
        <!-- Traffic sources -->
        <div class="card">
            <div class="card-header header-elements-inline">
                <h6 class="card-title text-uppercase">Seleccionar flujo de trabajo</h6>
            </div>
            <div class="card-body">
                {!! Form::open(array('route' => 'seguimiento.buscaremisor', 'method' => 'POST' ,'onsubmit' => 'return false;', 'role' => 'form', 'autocomplete' => 'off', 'id' => 'formBusqueda'.$entidad))  !!}
                {!! Form::hidden('page', 1, array('id' => 'page')) !!}
                {!! Form::hidden('filas', 40, array('id' => 'filas')) !!}
                {!! Form::hidden('accion', 'listar', array('id' => 'accion')) !!}
                <div class="form-group row">
                    <label for="flujotrabajo_id" class="col-lg-3 col-form-label">Flujo de trabajo:</label>
                    <div class="col-lg-9">
                        {!! Form::select('flujotrabajo_id', $cboFlujotrabajo, NULL, array('class' => 'form-control form-control-select2', 'id' => 'flujotrabajo_id')) !!}
                    </div>
                </div>
                <div class="text-right">
                    {!! Form::button('Buscar <i class="icon-search4"></i>', array('class' => 'btn btn-success btn-sm', 'id' => 'btnBuscar', 'onclick' => 'actualizar();')) !!}
                    {!! Form::button('Emitir <i class="icon-add"></i>', array('class' => 'btn btn-info btn-sm', 'id' => 'btnNuevo', 'onclick' => 'emitirdocumento();')) !!}
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xl-12">
        <!-- Traffic sources -->
        <div class="card">
            <div class="card-header header-elements-inline">
                <h6 class="card-title text-uppercase">Detalle de flujo de trabajo</h6>
            </div>
            <div id="listado{{ $entidad }}">
            </div>
        </div>
    </div>
</div>
<div class="card-group-control card-group-control-left" id="accordion-control">

</div>

<script type="text/javascript">
    $(document).ready(function () {
        $(IDFORMBUSQUEDA + '{!! $entidad !!} :input[id="flujotrabajo_id"]').select2({});
        let ireceptor = $("#i-receptor");
        let iemisor = $("#i-emisor");
        iemisor.removeClass('text-default-300');
        iemisor.addClass('text-purple-300');
        ireceptor.removeClass('text-purple-300');
        ireceptor.addClass('text-default-300');
    });

    function emitirdocumento() {
        let flujotrabajo_id = $(IDFORMBUSQUEDA + '{!! $entidad !!} :input[id="flujotrabajo_id"]').val();
        if (flujotrabajo_id !== "") {
            let url = "{{ URL::route('documento.create') }}?flujotrabajo_id=" + flujotrabajo_id;
            modal(url, 'Registrar Documentos');
        }else{
            alert("Seleccionar un flujo de trabajo")
        }
    }

    function actualizar() {
        let flujotrabajo_id = $(IDFORMBUSQUEDA + '{!! $entidad !!} :input[id="flujotrabajo_id"]').val();
        if (flujotrabajo_id !== "") {
            buscar('{{ $entidad }}');
            let url = "{{ URL::route('seguimiento.buscartareasemisor', array("")) }}/" + flujotrabajo_id;
            cargarRuta(url, 'accordion-control');
        }else{
            alert("Seleccionar un flujo de trabajo")
        }
    }
</script>

resources/views/dashboard/footer.blade.php
<div class="navbar navbar-expand-lg navbar-light">
    <div class="text-center d-lg-none w-100">
        <button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse"
                data-target="#navbar-footer">
            <i class="icon-unfold mr-2"></i>
            Footer
        </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-footer">
        <span class="navbar-text">
            &copy; 2019. <a href="#">Sigillum</a>
        </span>
    </div>
</div>
{!! Html::script('plugins/chosen/chosen.jquery.js') !!}
{!! Html::script('plugins/bloodhound/bloodhound.min.js') !!}
{!! Html::script('plugins/bloodhound/typeahead.bundle.min.js') !!}

resources/views/dashboard/main.blade.php
{{--Page header--}}
@section('pageheader')
    <div id="cabecerahome" class="page-header page-header-light">
        <div class="page-header-content header-elements-md-inline">
            <div class="page-title d-flex">
                <div class="d-flex justify-content-center">
                    <a onclick="cargarRuta('{{ URL::route('home.receptor') }}', 'contenido');" class="btn btn-link btn-float font-weight-semibold text-default">
                        <i id="i-receptor" class="icon-hour-glass2 text-default-300"></i>
                        <span>Pendientes</span>
                    </a>
                    <a onclick="cargarRuta('{{ URL::route('home.emisor') }}', 'contenido');" class="btn btn-link btn-float font-weight-semibold text-default">
                        <i id="i-emisor" class="icon-folder-upload text-default-300"></i>
                        <span>Emitidos</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
@show
{{--/page header--}}

{{--Content area--}}
@section('contenido')
    <div class="content" id="contenido">
        @yield('contenido')
    </div>
@show
{{--/content area--}}

{{--Footer--}}
@include('dashboard.footer')
{{--/footer--}}
<script>
    $(document).ready(function () {
        cargarRuta('{{ URL::route('home.receptor') }}', 'contenido');

    });
</script>

resources/views/dashboard/navbar.blade.php
<?php

use App\Representante;
use Illuminate\Support\Facades\Auth;

$user = Auth::user();
session(['usertype_id' => $user->usertype_id]);
$tipousuario_id = session('usertype_id');
$person = Representante::find($user->representante_id);
?>
<div class="navbar navbar-expand-md navbar-dark bg-indigo navbar-static fixed-top">
    <div class="navbar-brand">
        <a href="{{ URL::route('home') }}" class="d-inline-block">
            <img src="global_assets/images/logo_light_2.png" alt="">
        </a>
    </div>

    <div class="d-md-none">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
            <i class="icon-tree5"></i>
        </button>
        <button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
            <i class="icon-paragraph-justify3"></i>
        </button>
    </div>

    <div class="collapse navbar-collapse" id="navbar-mobile">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="#" class="navbar-nav-link sidebar-control sidebar-main-toggle d-none d-md-block">
                    <i class="icon-paragraph-justify3"></i>
                </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown dropdown-user">
                <a href="#" class="navbar-nav-link dropdown-toggle" data-toggle="dropdown">
                    <img src="{{ $user->avatar_url }}" class="rounded-circle" alt="">
                    <span>{{ $person->nombres }}</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a href="logout" class="dropdown-item"><i class="icon-switch2"></i> Cerrar sesión</a>
                </div>
            </li>
        </ul>
    </div>
</div>

resources/views/dashboard/receptor.blade.php
<div class="row">
    <div class="col-xl-12">
        <!-- Traffic sources -->
        <div class="card">
            <div class="card-header header-elements-inline">
                <h6 class="card-title text-uppercase">Seleccionar flujo de trabajo</h6>
            </div>
            <div class="card-body">
                {!! Form::open(array('route' => 'seguimiento.buscar', 'method' => 'POST' ,'onsubmit' => 'return false;', 'role' => 'form', 'autocomplete' => 'off', 'id' => 'formBusqueda'.$entidad))  !!}
                {!! Form::hidden('page', 1, array('id' => 'page')) !!}
                {!! Form::hidden('filas', 40, array('id' => 'filas')) !!}
                {!! Form::hidden('accion', 'listar', array('id' => 'accion')) !!}
                <div class="form-group row">
                    <label for="flujotrabajo_id" class="col-lg-3 col-form-label">Flujo de trabajo:</label>
                    <div class="col-lg-9">
                        {!! Form::select('flujotrabajo_id', $cboFlujotrabajo, NULL, array('class' => 'form-control form-control-select2', 'id' => 'flujotrabajo_id')) !!}
                    </div>
                </div>
                <div class="text-right">
                    {!! Form::button('Buscar <i class="icon-search4"></i>', array('class' => 'btn btn-success btn-sm', 'id' => 'btnBuscar', 'onclick' => 'actualizar();')) !!}
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xl-12">
        <!-- Traffic sources -->
        <div class="card">
            <div class="card-header header-elements-inline">
                <h6 class="card-title text-uppercase">Detalle de flujo de trabajo</h6>
            </div>
            <div id="listado{{ $entidad }}">
            </div>
        </div>
    </div>
</div>
<div class="card-group-control card-group-control-left" id="accordion-control">

</div>

<script type="text/javascript">
    $(document).ready(function () {
        $(IDFORMBUSQUEDA + '{!! $entidad !!} :input[id="flujotrabajo_id"]').select2({});
        let ireceptor = $("#i-receptor");
        let iemisor = $("#i-emisor");
        ireceptor.removeClass('text-default-300');
        ireceptor.addClass('text-purple-300');
        iemisor.removeClass('text-purple-300');
        iemisor.addClass('text-default-300');
    });

    function actualizar() {
        let flujotrabajo_id = $(IDFORMBUSQUEDA + '{!! $entidad !!} :input[id="flujotrabajo_id"]').val();
        if (flujotrabajo_id !== "") {
            buscar('{{ $entidad }}');
            let url = "{{ URL::route('seguimiento.buscartareas', array("")) }}/" + flujotrabajo_id;
            cargarRuta(url, 'accordion-control');
        } else {
            alert("Seleccionar un flujo de trabajo")
        }

    }
</script>

resources/views/dashboard/sidebar.blade.php
<?php

use App\Representante;
use Illuminate\Support\Facades\Auth;

$user = Auth::user();
$person = Representante::find($user->representante_id);
?>
<div class="sidebar sidebar-light sidebar-main sidebar-fixed sidebar-expand-md">

    {{-- Sidebar mobile toggler --}}
    <div class="sidebar-mobile-toggler text-center">
        <a href="#" class="sidebar-mobile-main-toggle">
            <i class="icon-arrow-left8"></i>
        </a>
        Navigation
        <a href="#" class="sidebar-mobile-expand">
            <i class="icon-screen-full"></i>
            <i class="icon-screen-normal"></i>
        </a>
    </div>
    {{-- /sidebar mobile toggler --}}

    {{-- Sidebar content --}}
    <div class="sidebar-content">

        {{-- User menu --}}
        <div class="sidebar-user-material">
            <div class="sidebar-user-material-body">
                <div class="card-body text-center">
                    <a href="#">
                        <img src="{{ $user->avatar_url }}"
                             class="img-fluid rounded-circle shadow-1 mb-3" width="80" height="80" alt="">
                    </a>
                    <h6 class="mb-0 text-white text-shadow-dark">{{ $person->apellidopaterno.' '.$person->apellidomaterno.', '.$person->nombres }}</h6>
                    <span class="font-size-sm text-white text-shadow-dark">{{ $user->unicotipousuario->tipousuario->nombre }}</span><br>
                    <span class="font-size-sm text-white text-shadow-dark">{{ $person->empresa->razonsocial }}</span>
                </div>
                <div class="sidebar-user-material-footer">
                    <a href="#user-nav"
                       class="d-flex justify-content-between align-items-center text-shadow-dark dropdown-toggle"
                       data-toggle="collapse"><span>Mi cuenta</span></a>
                </div>
            </div>
            <div class="collapse" id="user-nav">
                <ul class="nav nav-sidebar">
                    <li class="nav-item">
                        <a href="#" onclick="modal('usuario/editdatos/{{ $user->id }}', 'Modificar datos')"
                           class="nav-link">
                            <i class="icon-user-plus"></i>
                            <span>Mis datos</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" onclick="modal('usuario/editclave/{{ $user->id }}', 'Modificar contraseña')"
                           class="nav-link">
                            <i class="icon-key"></i>
                            <span>Cambiar Contraseña</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="logout" class="nav-link">
                            <i class="icon-switch2"></i>
                            <span>Cerrar Sesión</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        {{-- /user menu --}}

        {{-- Main navigation --}}
        <div class="card card-sidebar-mobile">
            <ul class="nav nav-sidebar" data-nav-type="accordion">

                {{-- Main --}}
                <li class="nav-item-header">
                    <div class="text-uppercase font-size-xs line-height-xs">Principal</div>
                    <i class="icon-menu" title="Main"></i>
                </li>
                <li class="nav-item">
                    <a onclick="cargarRuta('{{ URL::route('home.main') }}', 'content');" class="nav-link">
                        <i class="icon-home4"></i>
                        <span>Inicio</span>
                    </a>
                </li>

                {!! $menu !!}

                {{-- /main --}}

            </ul>
        </div>
        {{-- /main navigation --}}

    </div>
    {{-- /sidebar content --}}

</div>