routes/web.php
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('logout', 'Auth\LoginController@logout');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/main', 'HomeController@main')->name('home.main');
    Route::get('/noautorizado/{tipo}', 'HomeController@noautorizado')->name('home.noautorizado');
    Route::get('emisor', 'HomeController@emisor')->name('home.emisor');
    Route::get('receptor', 'HomeController@receptor')->name('home.receptor');
    Route::post('categoriamenu/buscar', 'CategoriamenuController@buscar')->name('categoriamenu.buscar');
    Route::get('categoriamenu/eliminar/{id}/{listarluego}', 'CategoriamenuController@eliminar')->name('categoriamenu.eliminar');
    Route::resource('categoriamenu', 'CategoriamenuController', array('except' => array('show')));

    Route::post('opcionmenu/buscar', 'OpcionmenuController@buscar')->name('opcionmenu.buscar');
    Route::get('opcionmenu/eliminar/{id}/{listarluego}', 'OpcionmenuController@eliminar')->name('opcionmenu.eliminar');
    Route::resource('opcionmenu', 'OpcionmenuController', array('except' => array('show')));

    Route::post('tipousuario/buscar', 'TipousuarioController@buscar')->name('tipousuario.buscar');
    Route::get('tipousuario/obtenerpermisos/{listar}/{id}', 'TipousuarioController@obtenerpermisos')->name('tipousuario.obtenerpermisos');
    Route::post('tipousuario/guardarpermisos/{id}/{permiso_id}/{accion}', 'TipousuarioController@guardarpermisos')->name('tipousuario.guardarpermisos');
    Route::get('tipousuario/eliminar/{id}/{listarluego}', 'TipousuarioController@eliminar')->name('tipousuario.eliminar');
    Route::resource('tipousuario', 'TipousuarioController', array('except' => array('show')));

    Route::resource('usuario', 'UsuarioController');
    Route::post('usuario/buscar', 'UsuarioController@buscar')->name('usuario.buscar');
    Route::get('usuario/eliminar/{id}/{listarluego}', 'UsuarioController@eliminar')->name('usuario.eliminar');
    Route::get('usuario/autocompletarrepresentante/{querysearch}', 'UsuarioController@autocompletarrepresentante')->name('usuario.autocompletarrepresentante');
    Route::get('usuario/activarusuario/{id}/{listarluego}', 'UsuarioController@activarusuario')->name('usuario.activarusuario');
    Route::post('usuario/activarcuenta/{id}', 'UsuarioController@activarcuenta')->name('usuario.activarcuenta');
    Route::get('usuario/editclave/{id}', 'UsuarioController@editclave')->name('usuario.editclave');
    Route::put('usuario/updateclave/{id}', 'UsuarioController@updateclave')->name('usuario.updateclave');
    Route::get('usuario/editdatos/{id}', 'UsuarioController@editdatos')->name('usuario.editdatos');
    Route::put('usuario/updatedatos/{id}', 'UsuarioController@updatedatos')->name('usuario.updatedatos');

    Route::post('permiso/buscar', 'PermisoController@buscar')->name('permiso.buscar');
    Route::get('permiso/eliminar/{id}/{listarluego}', 'PermisoController@eliminar')->name('permiso.eliminar');
    Route::resource('permiso', 'PermisoController', array('except' => array('show')));

    Route::post('empresa/buscar', 'EmpresaController@buscar')->name('empresa.buscar');
    Route::get('empresa/eliminar/{id}/{listarluego}', 'EmpresaController@eliminar')->name('empresa.eliminar');
    Route::resource('empresa', 'EmpresaController', array('except' => array('show')));

    Route::post('representante/buscar', 'RepresentanteController@buscar')->name('representante.buscar');
    Route::get('representante/eliminar/{id}/{listarluego}', 'RepresentanteController@eliminar')->name('representante.eliminar');
    Route::resource('representante', 'RepresentanteController', array('except' => array('show')));

    Route::post('tipodocumento/buscar', 'TipodocumentoController@buscar')->name('tipodocumento.buscar');
    Route::get('tipodocumento/eliminar/{id}/{listarluego}', 'TipodocumentoController@eliminar')->name('tipodocumento.eliminar');
    Route::resource('tipodocumento', 'TipodocumentoController', array('except' => array('show')));

    Route::post('metadata/buscar', 'MetadataController@buscar')->name('metadata.buscar');
    Route::get('metadata/eliminar/{id}/{listarluego}', 'MetadataController@eliminar')->name('metadata.eliminar');
    Route::resource('metadata', 'MetadataController', array('except' => array('show')));

    Route::post('flujotrabajo/buscar', 'FlujotrabajoController@buscar')->name('flujotrabajo.buscar');
    Route::get('flujotrabajo/eliminar/{id}/{listarluego}', 'FlujotrabajoController@eliminar')->name('flujotrabajo.eliminar');
    Route::get('flujotrabajo/verdocumentos/{flujotrabajo_id}', 'FlujotrabajoController@verdocumentos')->name('flujotrabajo.documentos');
    Route::resource('flujotrabajo', 'FlujotrabajoController', array('except' => array('show')));

    Route::post('documento/buscar', 'DocumentoController@buscar')->name('documento.buscar');
    Route::post('documento/guardar', 'DocumentoController@guardar')->name('documento.guardar');
    Route::get('documento/eliminar/{id}/{listarluego}', 'DocumentoController@eliminar')->name('documento.eliminar');
    Route::get('documento/emitir', 'DocumentoController@emitir')->name('documento.emitir');
    Route::get('documento/generarmetadata/{tipodocumento_id}/{documento_id?}', 'DocumentoController@generarmetadata')->name('documento.generarmetadata');
    Route::resource('documento', 'DocumentoController');

    Route::post('datos/buscar', 'DatosController@buscar')->name('datos.buscar');
    Route::get('datos/eliminar/{id}/{listarluego}', 'DatosController@eliminar')->name('datos.eliminar');
    Route::resource('datos', 'DatosController', array('except' => array('show')));

    Route::post('tarea/buscar', 'TareaController@buscar')->name('tarea.buscar');
    Route::get('tarea/eliminar/{id}/{listarluego}', 'TareaController@eliminar')->name('tarea.eliminar');
    Route::resource('tarea', 'TareaController', array('except' => array('show')));

    Route::post('bitacora/buscar', 'BitacoraController@buscar')->name('bitacora.buscar');
    Route::get('bitacora/eliminar/{id}/{listarluego}', 'BitacoraController@eliminar')->name('bitacora.eliminar');
    Route::resource('bitacora', 'BitacoraController', array('except' => array('show')));

    Route::post('respuesta/buscar', 'RespuestaController@buscar')->name('respuesta.buscar');
    Route::get('respuesta/eliminar/{id}/{listarluego}', 'RespuestaController@eliminar')->name('respuesta.eliminar');
    Route::resource('respuesta', 'RespuestaController', array('except' => array('show')));

    Route::post('detalleflujotrabajo/buscar', 'DetalleflujotrabajoController@buscar')->name('detalleflujotrabajo.buscar');
    Route::get('detalleflujotrabajo/eliminar/{id}/{listarluego}', 'DetalleflujotrabajoController@eliminar')->name('detalleflujotrabajo.eliminar');
    Route::resource('detalleflujotrabajo', 'DetalleflujotrabajoController', array('except' => array('show')));

    Route::post('seguimiento/buscar', 'SeguimientoController@buscar')->name('seguimiento.buscar');
    Route::get('seguimiento/eliminar/{id}/{listarluego}', 'SeguimientoController@eliminar')->name('seguimiento.eliminar');
    Route::get('seguimiento/buscartareas/{flujotrabajo_id}', 'SeguimientoController@buscartareas')->name('seguimiento.buscartareas');
    Route::get('seguimiento/documentosportarea/{detalleflujotrabajo_id}', 'SeguimientoController@documentosportarea')->name('seguimiento.documentosportarea');
    Route::resource('seguimiento', 'SeguimientoController', array('except' => array('show')));

    Route::post('seguimiento/buscaremisor', 'SeguimientoController@buscaremisor')->name('seguimiento.buscaremisor');
    Route::get('seguimiento/buscartareasemisor/{flujotrabajo_id}', 'SeguimientoController@buscartareasemisor')->name('seguimiento.buscartareasemisor');
    Route::get('seguimiento/documentosportareaemisor/{detalleflujotrabajo_id}', 'SeguimientoController@documentosportareaemisor')->name('seguimiento.documentosportareaemisor');

    Route::post('regla/buscar', 'ReglaController@buscar')->name('regla.buscar');
    Route::get('regla/eliminar/{id}/{listarluego}', 'ReglaController@eliminar')->name('regla.eliminar');
    Route::resource('regla', 'ReglaController', array('except' => array('show')));

    Route::post('historial/buscar', 'HistorialController@buscar')->name('historial.buscar');
    Route::get('historial/eliminar/{id}/{listarluego}', 'HistorialController@eliminar')->name('historial.eliminar');
    Route::resource('historial', 'HistorialController', array('except' => array('show')));
    Route::get('historial/documento/{documento}', 'HistorialController@historialdocumento')->name('historial.historialdocumento');
    Route::get('historial/verarchivos', 'HistorialController@verarchivos')->name('historial.verarchivos');

    Route::post('metadataregla/buscar', 'MetadatareglaController@buscar')->name('metadataregla.buscar');
    Route::get('metadataregla/eliminar/{id}/{listarluego}', 'MetadatareglaController@eliminar')->name('metadataregla.eliminar');
    Route::resource('metadataregla', 'MetadatareglaController', array('except' => array('show')));

    Route::post('respuestadetalleflujo/buscar', 'RespuestadetalleflujoController@buscar')->name('respuestadetalleflujo.buscar');
    Route::get('respuestadetalleflujo/eliminar/{id}/{listarluego}', 'RespuestadetalleflujoController@eliminar')->name('respuestadetalleflujo.eliminar');
    Route::resource('respuestadetalleflujo', 'RespuestadetalleflujoController', array('except' => array('show')));

    Route::get('archivo/mostrararchivo/{idarchivo}', 'ArchivoController@mostrararchivo')->name('archivo.mostrararchivo');


    Route::get('reporte/documento/{documento_id}', 'ReporteController@documentopdf')->name('reporte.documentopdf');
});

app/Detalleflujotrabajo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Detalleflujotrabajo extends Model
{
    use SoftDeletes;

    protected $table = 'detalle_flujotrabajo';
    protected $dates = ['deleted_at'];

    /**
     * @param $query
     * @param $nombre
     * @param $flujotrabajo_id
     * @return mixed
     */
    public function scopelistar($query, $nombre, $flujotrabajo_id)
    {
        return $query->join('tarea', 'detalle_flujotrabajo.tarea_id', 'tarea.id')
            ->where(function ($subquery) use ($nombre, $flujotrabajo_id) {
                if (!is_null($nombre)) {
                    $subquery->where('detalle_flujotrabajo.secuencia', 'LIKE', '%' . $nombre . '%');
                }
                if (!is_null($flujotrabajo_id)) {
                    $subquery->where('detalle_flujotrabajo.flujotrabajo_id', $flujotrabajo_id);
                }
            })->where('tarea.editable', 1)
            ->whereNull('tarea.deleted_at')
            ->select('detalle_flujotrabajo.*')
            ->orderBy('detalle_flujotrabajo.secuencia', 'ASC');
    }

    /**
     * @return BelongsTo
     */
    public function tarea()
    {
        return $this->belongsTo('App\Tarea', 'tarea_id');
    }

    /**
     * @return BelongsTo
     */
    public function flujotrabajo()
    {
        return $this->belongsTo('App\Flujotrabajo', 'flujotrabajo_id');
    }

    public function detalletipousuarios()
    {
        return $this->hasMany('App\Detalleflujotrabajotipousuario', 'detalleflujotrabajo_id');
    }

    /**
     * @param $query
     * @param $secuencia
     * @param $flujotrabajo_id
     * @return mixed
     */
    public function scopesiguiente($query, $secuencia, $flujotrabajo_id)
    {
        return $query->join('tarea', 'detalle_flujotrabajo.tarea_id', 'tarea.id')
            ->where('tarea.editable', 1)
            ->whereNull('tarea.deleted_at')
            ->where('detalle_flujotrabajo.flujotrabajo_id', $flujotrabajo_id)
            ->where('detalle_flujotrabajo.secuencia', '>', $secuencia)
            ->orderBy('detalle_flujotrabajo.secuencia', 'ASC')
            ->select('detalle_flujotrabajo.*')
            ->first();
    }

    /**
     * @param $query
     * @param $secuencia
     * @param $flujotrabajo_id
     * @return mixed
     */
    public function scopeanterior($query, $secuencia, $flujotrabajo_id)
    {
        return $query->join('tarea', 'detalle_flujotrabajo.tarea_id', 'tarea.id')
            ->where('tarea.editable', 1)
            ->whereNull('tarea.deleted_at')
            ->where('detalle_flujotrabajo.flujotrabajo_id', $flujotrabajo_id)
            ->where('detalle_flujotrabajo.secuencia', '<', $secuencia)
            ->select('detalle_flujotrabajo.*')
            ->orderBy('detalle_flujotrabajo.secuencia', 'DESC')->first();
    }

    /**
     * @param $query
     * @param $flujotrabajo_id
     * @return |null
     */
    public function scopeinicio($query, $flujotrabajo_id)
    {
        return $query->where('flujotrabajo_id', $flujotrabajo_id)->where('secuencia', 'I')->first();
    }

    /**
     * @param $query
     * @param $flujotrabajo_id
     * @return |null
     */
    public function scopefin($query, $flujotrabajo_id)
    {
        return $query->where('flujotrabajo_id', $flujotrabajo_id)->where('secuencia', 'F')->first();
    }

    /**
     * @param $query
     * @param $secuencia
     * @param $flujotrabajo_id
     * @return |null
     */
    public function scopenodo($query, $secuencia, $flujotrabajo_id)
    {
        $anterior = null;
        $detalle = $query->where('flujotrabajo_id', $flujotrabajo_id)->where('secuencia', $secuencia)->first();
        if (!is_null($detalle)) {
            $anterior = $detalle;
        }
        return $anterior;
    }

    /**
     * @return BelongsToMany
     */
    public function tipousuarios()
    {
        return $this->belongsToMany('App\Tipousuario', 'detalleflujotrabajo_tipousuario', 'detalleflujotrabajo_id', 'tipousuario_id')
            ->whereNull('detalleflujotrabajo_tipousuario.deleted_at')
            ->withTimestamps();

    }

    /**
     * @param $query
     * @param $flujotrabajo_id
     * @param bool $incluiriniciofin
     * @return mixed
     */
    public function scopedetalleporflujotrabajo($query, $flujotrabajo_id, $incluiriniciofin = false)
    {
        return $query->join('tarea', 'detalle_flujotrabajo.tarea_id', 'tarea.id')
            ->where('detalle_flujotrabajo.flujotrabajo_id', $flujotrabajo_id)
            ->whereNull('tarea.deleted_at')
            ->where(function ($subquery) use ($incluiriniciofin) {
                if (!$incluiriniciofin) {
                    $subquery->where('tarea.editable', 1);
                }
            })
            ->select('detalle_flujotrabajo.*');
    }

    /**
     * @param $query
     * @param $flujotrabajo_id
     * @return mixed
     */
    public function scopepasoinicial($query, $flujotrabajo_id)
    {
        return $query->where('flujotrabajo_id', $flujotrabajo_id)->where('secuencia', 'I');
    }
}

resources/views/app/detalleflujotrabajo/admin.blade.php
@php
    use Illuminate\Support\Facades\URL;
    $base = URL::to('/') . '/';
@endphp

<div class="card-header header-elements-inline">
    <h5 class="card-title">Búsqueda de {{ $title }}</h5>
    <div class="header-elements">
        <div class="list-icons">

        </div>
    </div>
</div>

<div class="card-body">
    {!! Form::open(array('route' => 'detalleflujotrabajo.buscar', 'method' => 'POST' ,'onsubmit' => 'return false;', 'role' => 'form', 'autocomplete' => 'off', 'id' => 'formBusqueda'.$entidad))  !!}
    {!! Form::hidden('page', 1, array('id' => 'page')) !!}
    {!! Form::hidden('flujotrabajo_id', $flujotrabajo_id, array('id' => 'flujotrabajo_id')) !!}
    {!! Form::hidden('filas', 40, array('id' => 'filas')) !!}
    {!! Form::hidden('accion', 'listar', array('id' => 'accion')) !!}
    <div class="text-right">
        {!! Form::button('Buscar <i class="icon-search4"></i>', array('class' => 'btn btn-success btn-sm', 'id' => 'btnBuscar', 'onclick' => 'buscar(\''.$entidad.'\')')) !!}
        {!! Form::button('Registrar <i class="icon-add"></i>', array('class' => 'btn btn-info btn-sm', 'id' => 'btnNuevo', 'onclick' => 'modal (\''.URL::route($ruta["create"], array('listar'=>'SI', 'flujotrabajo_id' => $flujotrabajo_id)).'\', \''.$titulo_registrar.'\', this);')) !!}
        {!! Form::button('Cerrar <i class="icon-paperplane"></i>', array('class' => 'btn btn-danger btn-sm', 'id' => 'btnBuscar', 'onclick' => 'cerrarModal();')) !!}
    </div>
    {!! Form::close() !!}
</div>
<div id="listado{{ $entidad }}">

</div>
<script>
    $(document).ready(function () {
        init(IDFORMBUSQUEDA + '{{ $entidad }}', 'B');
        buscar('{{ $entidad }}');
        configurarAnchoModal('800');
    });
</script>

resources/views/app/detalleflujotrabajo/list.blade.php
@if(count($lista) == 0)
    <h3 class="text-warning">No se encontraron resultados.</h3>
@else
    <table id="datatable-basic-detalle" class="table datatable-basic" style="width:100%">
        <thead>
        <tr>
            @foreach($cabecera as $key => $value)
                <th @if((int)$value['numero'] > 1) colspan="{{ $value['numero'] }}" @endif>{!! $value['valor'] !!}</th>
            @endforeach
        </tr>
        </thead>
        <tbody>
        <?php
        $contador = $inicio + 1;
        $contadortipousuarios = 0;
        ?>
        @foreach ($lista as $key => $value)
            <tr>
                <td>{{ $value->secuencia }}</td>
                <td>{{ $value->tarea->descripcion }}</td>
                <td>
                    @if($value->editararchivos)
                        {{ 'SI' }}
                    @else
                        {{ 'NO' }}
                    @endif
                </td>
                <td>
                    @foreach($value->detalletipousuarios as $keytipousuario => $valuetipousuario)
                        @if($contadortipousuarios === 0)
                            <span class="badge badge-dark badge-pill">{{ $valuetipousuario->tipousuario->empresa->razonsocial }} - {{ $valuetipousuario->tipousuario->nombre }}</span>
                        @else
                            <br><span class="badge badge-dark badge-pill">{{ $valuetipousuario->tipousuario->empresa->razonsocial }} - {{ $valuetipousuario->tipousuario->nombre }}</span>
                        @endif
                        @php
                            $contadortipousuarios++;
                        @endphp
                    @endforeach
                </td>
                <td>{!! Form::button('<i class="icon-bubbles4"></i> Respuestas', array('onclick' => 'modal (\''.URL::route('respuestadetalleflujo.index', array('detalleflujotrabajo_id'=>$value->id)).'\', \''.$value->tarea->descripcion.'\', this);', 'class' => 'btn btn-sm btn-default')) !!}</td>
                <td>{!! Form::button('<i class="icon-pencil4"></i> Editar', array('onclick' => 'modal (\''.URL::route($ruta["edit"], array($value->id, 'listar'=>'SI')).'\', \''.$titulo_modificar.'\', this);', 'class' => 'btn btn-warning btn-sm')) !!}</td>
                <td>{!! Form::button('<i class="icon-cross2"></i> Eliminar', array('onclick' => 'modal (\''.URL::route($ruta["delete"], array($value->id, 'SI')).'\', \''.$titulo_eliminar.'\', this);', 'class' => 'btn btn-danger btn-sm')) !!}</td>
            </tr>
            <?php
            $contador = $contador + 1;
            ?>
        @endforeach
        </tbody>
        <tfoot>
        <tr>
            @foreach($cabecera as $key => $value)
                <th @if((int)$value['numero'] > 1) colspan="{{ $value['numero'] }}" @endif>{!! $value['valor'] !!}</th>
            @endforeach
        </tr>
        </tfoot>
    </table>
    <script>
        $(document).ready(function () {
            // Basic datatable
            $('#datatable-basic-detalle').DataTable({
                pageLength: 100,
                responsive: true,
                "scrollX": true,
                "searching": false
            });
        });
    </script>
@endif

resources/views/app/detalleflujotrabajo/mant.blade.php
<div id="divMensajeError{!! $entidad !!}"></div>
{!! Form::model($detalleflujotrabajo, $formData) !!}
{!! Form::hidden('listar', $listar, array('id' => 'listar')) !!}
{!! Form::hidden('flujotrabajo_id', $flujotrabajo_id, array('id' => 'flujotrabajo_id')) !!}
<div class="form-group row">
    {!! Form::label('tarea_id', 'Tarea:', array('class' => 'col-lg-3 col-md-3 col-sm-3 col-form-label')) !!}
    <div class="col-lg-9 col-md-9 col-sm-9">
        {!! Form::select('tarea_id', $cboTarea, NULL, array('class' => 'form-control select', 'id' => 'tarea_id')) !!}
    </div>
</div>
<div class="form-group row">
    {!! Form::label('secuencia', 'Secuencia:', array('class' => 'col-lg-3 col-md-3 col-sm-3 col-form-label')) !!}
    <div class="col-lg-9 col-md-9 col-sm-9">
        {!! Form::text('secuencia', null, array('class' => 'form-control', 'id' => 'secuencia', 'placeholder' => 'Ingrese secuencia')) !!}
    </div>
</div>
<div class="form-group row">
    {!! Form::label('editararchivos', '¿Modificar archivos?:', array('class' => 'col-lg-3 col-md-3 col-sm-3 col-form-label')) !!}
    <div class="col-lg-9 col-md-9 col-sm-9">
        {!! Form::checkbox('editararchivos', 1, null, array('class' => 'form-check-input-styled')) !!}
    </div>
</div>
<div class="form-group row">
    {!! Form::label('tipousuario_id', 'Tipos de usuario', array('class' => 'col-lg-3 col-md-3 col-sm-3 col-form-label')) !!}
    <div class="col-lg-9 col-md-9 col-sm-9">
        {!! Form::select('tipousuario_id[]', $cboTipousuario, !is_null($detalleflujotrabajo) ? $detalleflujotrabajo->tipousuarios->pluck('id')->toArray() : null,
        array(
        'data-placeholder' => 'Seleccionar tipos de usuario',
        'multiple' => 'multiple',
        'class' => 'form-control form-control-select2',
        'id' => 'tipousuario_id')) !!}
    </div>
</div>
<div class="form-group row">
    <div class="col-lg-12 col-md-12 col-sm-12 text-right">
        {!! Form::button('<i class="fa fa-check fa-lg"></i> '.$boton, array('class' => 'btn btn-success btn-sm', 'id' => 'btnGuardar', 'onclick' => 'guardar(\''.$entidad.'\', this)')) !!}
        {!! Form::button('<i class="fa fa-exclamation fa-lg"></i> Cancelar', array('class' => 'btn btn-warning btn-sm', 'id' => 'btnCancelar'.$entidad, 'onclick' => 'cerrarModal();')) !!}
    </div>
</div>
{!! Form::close() !!}
<script type="text/javascript">
    $(document).ready(function () {
        let idmodal = '#modal' + (contadorModal - 1);
        $(IDFORMMANTENIMIENTO + '{!! $entidad !!} :input[id="tarea_id"]').select2({
            dropdownParent: $(idmodal)
        });
        $(IDFORMMANTENIMIENTO + '{!! $entidad !!} :input[id="tipousuario_id"]').select2({
            dropdownParent: $(idmodal)
        });
        $(IDFORMMANTENIMIENTO + '{!! $entidad !!} :input[id="editararchivos"]').uniform();
        configurarAnchoModal('620');
        init(IDFORMMANTENIMIENTO + '{!! $entidad !!}', 'M');
    });
</script>